version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: $env:DOCKERFILEPATH_API
    ports:
      - "7106:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=$env:ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__DefaultConnection=$env:DB_CONNECTION_STRING
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: $env:DB_PASSWORD
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
